version: '3.8'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7.33
    restart: always
    ports:
      - "3666:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./conf/mysql/my.cnf:/etc/my.cnf"
    environment:
      - "MYSQL_ROOT_PASSWORD=R(E8gamA"
      - "TZ=Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "6G"
    networks:
         vmnet:
            ipv4_address: 172.19.0.2


  nacos:
    container_name: nacos
    image: nacos/nacos-server:2.0.3
    restart: always
    ports:
      - "8848:8848"
    volumes:
      - "./conf/nacos/application.properties:/home/nacos/conf/application.properties"
    environment:
      - "MODE=standalone"
      - "MYSQL_SERVICE_HOST=172.19.0.2"
      - "MYSQL_SERVICE_PORT=3306"
      - "MYSQL_SERVICE_DB_NAME=nacos"
      - "MYSQL_SERVICE_USER=root"
      - "MYSQL_SERVICE_PASSWORD=R(E8gamA"
      - "MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false"
      - "MYSQL_DATABASE_NUM=1"
      - "TZ=Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
         vmnet:
            ipv4_address: 172.19.0.3
    depends_on:
      - "mysql"


  redis:
    container_name: redis
    image: redis:4.0.9
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis/:/data"
    environment:
      - "TZ=Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "6G"
    networks:
         vmnet:
            ipv4_address: 172.19.0.4


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.8-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - "./data/rabbitmq/:/var/lib/rabbitmq"
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=sfsj_admin"
      - "TZ=Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
         vmnet:
            ipv4_address: 172.19.0.5


  apisix:
    container_name: apisix
    image: apache/apisix:3.6.0-centos
    restart: always
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    volumes:
      - "./conf/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro"
    environment:
      - "TZ=Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
         vmnet:
            ipv4_address: 172.19.0.6
    depends_on:
      - "etcd"
      - "nacos"


  apisix-dashboard:
    container_name: apisix-dashboard
    image: apache/apisix-dashboard:3.0.1-centos
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "./conf/apisix_dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "500M"
    networks:
         vmnet:
            ipv4_address: 172.19.0.7
    depends_on:
      - "etcd"
      - "apisix"


  etcd:
    container_name: etcd
    image: bitnami/etcd:3.4.15
    restart: always
    ports:
      - "2379:2379/tcp"
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://172.19.0.8:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://172.19.0.8:2379"
      TZ: "Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
         vmnet:
            ipv4_address: 172.19.0.8


  xxl-lob:
    container_name: xxl-job
    image: xuxueli/xxl-job-admin:2.4.0
    restart: always
    ports:
      - "8080:8080"
    environment:
       PARAMS: "--spring.datasource.url=jdbc:mysql://172.19.0.2:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.username=root --spring.datasource.password=R(E8gamA"
       TZ: "Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "3G"
    networks:
         vmnet:
            ipv4_address: 172.19.0.9
    depends_on:
      - "mysql"

  mongodb:
    image: mongo:5.0.22
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo/:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
      - "TZ=Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
          vmnet:
            ipv4_address: 172.19.0.10


  mongo-express:
    image: mongo-express:1.0.0-20
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=admin"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=admin"
      - "ME_CONFIG_MONGODB_SERVER=mongodb"   #web default user:admin passwd:pass
      - "TZ=Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "500M"
    networks:
          vmnet:
            ipv4_address: 172.19.0.11


networks:
    vmnet:
      ipam:
         config:
         - subnet: 172.19.0.0/16