version: '3.8'

services:

  mysql-dev:
    image: mysql:5.7.33
    ports:
      - "3306:3306"
    volumes:
      - "./mount/mysql:/var/lib/mysql"
      - "./conf/mysql/my.cnf:/etc/my.cnf"
    environment:
      - "MYSQL_ROOT_PASSWORD=R(E8gamA"
      - "TZ=Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.50"
          memory: "6G"
    networks:
      - vmnet


  nacos-dev:
    image: nacos/nacos-server:2.0.3
    ports:
      - "8848:8848"
    volumes:
      - "./conf/nacos/application.properties:/home/nacos/conf/application.properties"
    environment:
      - "MODE=standalone"
      - "MYSQL_SERVICE_HOST=mysql-dev"
      - "MYSQL_SERVICE_PORT=3306"
      - "MYSQL_SERVICE_DB_NAME=nacos"
      - "MYSQL_SERVICE_USER=root"
      - "MYSQL_SERVICE_PASSWORD=R(E8gamA"
      - "MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false"
      - "MYSQL_DATABASE_NUM=1"
      - "TZ=Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
      - vmnet
    depends_on:
      - "mysql-dev"


  redis-dev:
    image: redis:4.0.9
    ports:
      - "6379:6379"
    volumes:
      - "./mount/redis/:/data"
      - "./conf/redis:/usr/local/etc/redis"
    environment:
      - "TZ=Asia/Shanghai"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.20"
          memory: "6G"
    networks:
      - vmnet


  rabbitmq-dev:
    image: rabbitmq:3.12.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - "./mount/rabbitmq/:/var/lib/rabbitmq"
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=sfsj_admin"
      - "TZ=Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
      - vmnet


  apisix:
    image: apache/apisix:3.3.0-centos
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    volumes:
      - "./conf/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro"
    environment:
      - "TZ=Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
      - vmnet
    depends_on:
      - "etcd"
      - "nacos-dev"

  web1:
    image: nginx:1.19.0-alpine
    volumes:
      - ./conf/apisix_web/nginx_1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.10"
          memory: "500M"
    logging:
      driver: "json-file"
      options:
        max-size: "512M"
    networks:
      - vmnet
    depends_on:
      - "apisix"


  web2:
    image: nginx:1.19.0-alpine
    volumes:
      - ./conf/apisix_web/nginx_2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.10"
          memory: "500M"
    logging:
      driver: "json-file"
      options:
        max-size: "512M"
    networks:
      - vmnet
    depends_on:
      - "apisix"


  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-centos
    ports:
      - "9000:9000"
    volumes:
      - "./conf/apisix_dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.10"
          memory: "500M"
    networks:
      -  vmnet
    depends_on:
      - "etcd"
      - "apisix"


  etcd:
    image: bitnami/etcd:3.4.15
    ports:
      - "2379:2379/tcp"
    volumes:
      - "./mount/etcd/data/:/bitnami/etcd/data/"
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      TZ: "Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
      - vmnet


  xxljob-dev:
    image: xuxueli/xxl-job-admin:2.4.0
    ports:
      - "8080:8080"
    environment:
       PARAMS: "--spring.datasource.url=jdbc:mysql://mysql-dev:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.username=root --spring.datasource.password=R(E8gamA --xxl.job.accessToken=4f9802e383b24d7e8b196df9dac0f77e"
       TZ: "Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.20"
          memory: "3G"
    networks:
      - vmnet
    depends_on:
      - "mysql-dev"

  mongodb-dev:
    image: mongo:5.0.22
    ports:
      - "27017:27017"
    volumes:
      - "./mount/mongo/:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
      - "TZ=Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.20"
          memory: "2G"
    networks:
       - vmnet





  mongo-express-dev:
    image: mongo-express:1.0.0-20
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=admin"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=admin"
      - "ME_CONFIG_MONGODB_SERVER=mongodb-dev"
      - "TZ=Asia/Shanghai"
    deploy:
      placement:
        constraints: [node.labels.type == master]
      resources:
        limits:
          cpus: "0.10"
          memory: "500M"
    networks:
       -  vmnet


networks:
    vmnet:
      driver: overlay
      external: true
